'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class IndexLocal
    
    '''<summary>
    '''form control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''ScriptManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''MainPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainPanel As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''AddNewItemButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddNewItemButton As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''InsertNewItemButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InsertNewItemButton As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''DecreaseItemIndentationButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DecreaseItemIndentationButton As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''IncreaseItemIndentationButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IncreaseItemIndentationButton As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''DeleteItemButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeleteItemButton As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''SetCustomBarColorToItemButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SetCustomBarColorToItemButton As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''CopyImageButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CopyImageButton As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''PasteImageButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PasteImageButton As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''MoveItemUpButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MoveItemUpButton As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''MoveItemDownButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MoveItemDownButton As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''SetCustomScalesButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SetCustomScalesButton As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ZoomInButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ZoomInButton As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''DecreaseTimelinePageButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DecreaseTimelinePageButton As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''IncreaseTimelinePageButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IncreaseTimelinePageButton As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ToggleBaselineButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToggleBaselineButton As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''HighlightCriticalPathButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HighlightCriticalPathButton As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''SplitRemainingWorkButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SplitRemainingWorkButton As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ToggleDependencyConstraintsButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToggleDependencyConstraintsButton As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''LevelResourcesButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LevelResourcesButton As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ScheduleChartButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScheduleChartButton As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''LoadChartButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LoadChartButton As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''PertChartButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PertChartButton As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''NetworkDiagramButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NetworkDiagramButton As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ProjectStatisticsButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProjectStatisticsButton As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''LoadProjectXmlButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LoadProjectXmlButton As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''SaveProjectXmlButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaveProjectXmlButton As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''PrintButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PrintButton As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''GanttChartView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GanttChartView As Global.DlhSoft.Web.UI.WebControls.GanttChartView
    
    '''<summary>
    '''LoadProjectXmlUpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LoadProjectXmlUpdatePanel As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''LoadProjectXmlPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LoadProjectXmlPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''LoadProjectXmlFileUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LoadProjectXmlFileUpload As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''LoadProjectXmlSubmitButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LoadProjectXmlSubmitButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''CloseLoadProjectXmlButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CloseLoadProjectXmlButton As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''ScheduleChartUpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScheduleChartUpdatePanel As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''ScheduleChartPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScheduleChartPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''CloseScheduleChartViewButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CloseScheduleChartViewButton As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''ScheduleChartView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScheduleChartView As Global.DlhSoft.Web.UI.WebControls.ScheduleChartView
    
    '''<summary>
    '''LoadChartUpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LoadChartUpdatePanel As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''LoadChartPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LoadChartPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''CloseLoadChartViewButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CloseLoadChartViewButton As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''LoadChartView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LoadChartView As Global.DlhSoft.Web.UI.WebControls.LoadChartView
    
    '''<summary>
    '''PertChartUpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PertChartUpdatePanel As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''PertChartPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PertChartPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ClosePertChartViewButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClosePertChartViewButton As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''PertChartView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PertChartView As Global.DlhSoft.Web.UI.WebControls.Pert.PertChartView
    
    '''<summary>
    '''NetworkDiagramUpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NetworkDiagramUpdatePanel As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''NetworkDiagramPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NetworkDiagramPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''CloseNetworkDiagramViewButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CloseNetworkDiagramViewButton As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''NetworkDiagramView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NetworkDiagramView As Global.DlhSoft.Web.UI.WebControls.Pert.NetworkDiagramView
End Class
